# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 926b378e506588b0b418c24b065dde8f43a888bf5f02506d0379594ed55aeef886402c4cf8f1f1105e5b27e765a4efe9eed54e998714120c17000dda46c59bb3

test:
  secret_key_base: b4cb229109cef3bf55c877151a428b17ecbac236859510e0b35e3ecf50bafb67aaf97584a9d5b2efa6251a72d4c30988e4d47f135e9ad5e5b30c93278295d31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
